# coding: utf-8
#
import uiautomator2 as u2

d = u2.connect()
d(resourceId="org.totschnig.myexpenses.debug:id/suw_navbar_next").click()
d(resourceId="org.totschnig.myexpenses.debug:id/suw_navbar_next").click()
d(resourceId="org.totschnig.myexpenses.debug:id/suw_navbar_next").click()
d(description="Open navigation drawer").click()
d(resourceId="org.totschnig.myexpenses.debug:id/headerIndicator").click()
d(resourceId="org.totschnig.myexpenses.debug:id/design_menu_item_text", text="New account").click()
d.widget.click("00001#")
d(resourceId="org.totschnig.myexpenses.debug:id/AccountType").click()
d(resourceId="android:id/text1", text="Bank account").click()
d(resourceId="org.totschnig.myexpenses.debug:id/Label").click()
d.send_keys("Bank Account", clear=True)
d(resourceId="org.totschnig.myexpenses.debug:id/CREATE_COMMAND").click()
d(resourceId="org.totschnig.myexpenses.debug:id/MANAGE_TEMPLATES_COMMAND").click()
d(description="Navigate up").click()
d(resourceId="org.totschnig.myexpenses.debug:id/CREATE_COMMAND").click()
d(description="Navigate up").click()
d(description="Open navigation drawer").click()
d(text="Bank accounts").click()
d(text="Bank accounts").click()
d.xpath('//*[@resource-id="org.totschnig.myexpenses.debug:id/accountList"]/android.view.View[1]/android.view.View[1]/android.view.View[2]').click()
d(resourceId="org.totschnig.myexpenses.debug:id/CREATE_COMMAND").click()
d.xpath('//*[@resource-id="org.totschnig.myexpenses.debug:id/MethodRow"]/android.widget.LinearLayout[1]').click()
d(resourceId="android:id/text1", text="Direct debit").click()
d(resourceId="org.totschnig.myexpenses.debug:id/TaType").click()